from __future__ import annotations

import subprocess
from pathlib import Path

from code_intelligence_agent.evaluation.v3_real_bug_reproduction import (
    audit_python_runtime,
    copy_test_overlay,
    execute_test_commands,
    materialize_preparation_files,
    prepare_real_bug_case,
    reproduce_real_bug_case,
)


def test_copy_test_overlay_copies_fix_test_and_rejects_escape(tmp_path):
    bug = tmp_path / "bug"
    fix = tmp_path / "fix"
    (bug / "tests").mkdir(parents=True)
    (fix / "tests").mkdir(parents=True)
    (bug / "tests" / "test_core.py").write_text("old", encoding="utf-8")
    (fix / "tests" / "test_core.py").write_text("new", encoding="utf-8")

    result = copy_test_overlay(bug, fix, ["tests/test_core.py", "../outside.py"])

    assert result["status"] == "fail"
    assert result["copied_count"] == 1
    assert result["errors"] == ["unsafe_test_overlay_path:../outside.py"]
    assert (bug / "tests" / "test_core.py").read_text(encoding="utf-8") == "new"


def test_prepare_case_uses_bug_and_fix_sha_and_overlays_tests(tmp_path):
    stale = tmp_path / "bug" / "repository_checkout" / "stale.txt"
    stale.parent.mkdir(parents=True)
    stale.write_text("contaminated", encoding="utf-8")
    calls = []

    def fake_checkout(**kwargs):
        calls.append(kwargs)
        root = Path(kwargs["output_dir"]) / "repository_checkout"
        (root / "tests").mkdir(parents=True)
        (root / "tests" / "test_core.py").write_text(
            "fixed-test" if "fix" in str(kwargs["output_dir"]) else "bug-test",
            encoding="utf-8",
        )
        return {
            "status": "pass",
            "reason": "fixture",
            "checkout_path": str(root),
            "ref": kwargs["ref"],
            "checkout_method": "fixture",
        }

    case = _case()
    preparation = prepare_real_bug_case(case, tmp_path, checkout=fake_checkout)

    assert preparation["status"] == "pass"
    assert [item["ref"] for item in calls] == ["a" * 40, "b" * 40]
    assert stale.exists() is False
    assert (
        Path(preparation["bug_root"]) / "tests" / "test_core.py"
    ).read_text(encoding="utf-8") == "fixed-test"


def test_materialize_preparation_files_writes_only_small_safe_files(tmp_path):
    result = materialize_preparation_files(
        tmp_path,
        [
            {
                "path": "_generated_version.py",
                "content": 'version = "benchmark"\n',
                "reason": "Generated by packaging in the upstream project.",
            },
            {
                "path": "../escaped.py",
                "content": "unsafe\n",
                "reason": "escape",
            },
        ],
    )

    assert result["status"] == "fail"
    assert result["written_count"] == 1
    assert result["repository_code_executed"] is False
    assert (tmp_path / "_generated_version.py").read_text(encoding="utf-8") == (
        'version = "benchmark"\n'
    )
    assert (tmp_path.parent / "escaped.py").exists() is False


def test_execute_commands_classifies_environment_blocker(tmp_path):
    def fake_runner(command, **kwargs):
        del command, kwargs
        return subprocess.CompletedProcess(
            args=[],
            returncode=1,
            stdout="",
            stderr="ModuleNotFoundError: No module named 'pytest'",
        )

    result = execute_test_commands(
        [["{python}", "-m", "pytest", "-q", "tests/test_core.py"]],
        repository_root=tmp_path,
        python_executable=Path(__file__),
        timeout=5,
        runner=fake_runner,
    )

    assert result["status"] == "fail"
    assert result["environment_blocker"] is True


def test_execute_commands_injects_isolated_home(tmp_path):
    observed_env = {}

    def fake_runner(command, **kwargs):
        del command
        observed_env.update(kwargs["env"])
        return subprocess.CompletedProcess(
            args=[],
            returncode=0,
            stdout="1 passed",
            stderr="",
        )

    result = execute_test_commands(
        [["{python}", "-m", "pytest", "-q", "tests/test_core.py"]],
        repository_root=tmp_path,
        python_executable=Path(__file__),
        timeout=5,
        runner=fake_runner,
    )

    expected_home = str((tmp_path / ".cia-test-home").resolve())
    assert result["status"] == "pass"
    assert observed_env["HOME"] == expected_home
    assert observed_env["USERPROFILE"] == expected_home


def test_execute_commands_injects_only_repository_pythonpath(tmp_path):
    docs_src = tmp_path / "docs_src"
    docs_src.mkdir()
    observed_env = {}

    def fake_runner(command, **kwargs):
        del command
        observed_env.update(kwargs["env"])
        return subprocess.CompletedProcess([], 0, stdout="1 passed", stderr="")

    result = execute_test_commands(
        [["{python}", "-m", "pytest", "-q", "tests"]],
        repository_root=tmp_path,
        python_executable=Path(__file__),
        timeout=5,
        runner=fake_runner,
        test_environment={"pythonpath_entries": ["docs_src"]},
    )

    assert result["status"] == "pass"
    assert observed_env["PYTHONPATH"] == str(docs_src.resolve())
    assert result["environment"]["pythonpath_entries"] == ["docs_src"]

    rejected = execute_test_commands(
        [["{python}", "-m", "pytest", "-q", "tests"]],
        repository_root=tmp_path,
        python_executable=Path(__file__),
        timeout=5,
        runner=fake_runner,
        test_environment={"pythonpath_entries": ["../outside"]},
    )
    assert rejected["status"] == "fail"
    assert rejected["reason"] == "unsafe_pythonpath_entry"

    optional = execute_test_commands(
        [["{python}", "-m", "pytest", "-q", "tests"]],
        repository_root=tmp_path,
        python_executable=Path(__file__),
        timeout=5,
        runner=fake_runner,
        test_environment={"optional_pythonpath_entries": ["not-created"]},
    )
    assert optional["status"] == "pass"
    assert optional["environment"]["optional_pythonpath_entries_missing"] == [
        "not-created"
    ]

    unsupported_tool = execute_test_commands(
        [["{python}", "-m", "pytest", "-q", "tests"]],
        repository_root=tmp_path,
        python_executable=Path(__file__),
        timeout=5,
        runner=fake_runner,
        test_environment={"required_tools": ["not-allowlisted"]},
    )
    assert unsupported_tool["status"] == "fail"
    assert unsupported_tool["reason"] == (
        "required_test_tool_missing:not-allowlisted"
    )


def test_reproduction_requires_bug_fail_fix_targeted_and_regression_pass(tmp_path):
    case = _case()
    preparation = {
        "status": "pass",
        "reason": "fixture",
        "bug_root": str(tmp_path / "bug"),
        "fix_root": str(tmp_path / "fix"),
        "bug_checkout": {"status": "pass", "ref": "a" * 40},
        "fix_checkout": {"status": "pass", "ref": "b" * 40},
        "test_overlay": {"status": "pass", "files": []},
    }
    (tmp_path / "bug").mkdir()
    (tmp_path / "fix").mkdir()
    calls = 0

    def fake_runner(command, **kwargs):
        nonlocal calls
        del kwargs
        if "-c" in command:
            return subprocess.CompletedProcess(command, 0, stdout="3.11.9\n", stderr="")
        calls += 1
        returncode = 1 if calls == 1 else 0
        output = "1 failed" if returncode else "1 passed"
        return subprocess.CompletedProcess(command, returncode, stdout=output, stderr="")

    result = reproduce_real_bug_case(
        case,
        preparation,
        python_executable=Path(__file__),
        runner=fake_runner,
    )

    assert result["status"] == "pass"
    assert result["acceptance"] == {
        "bug_targeted_failed": True,
        "fix_targeted_passed": True,
        "fix_full_regression_passed": True,
        "reproducible": True,
    }
    assert result["gold_patch_visible_to_execution"] is False


def test_reproduction_rejects_zero_test_regression(tmp_path):
    case = _case()
    preparation = {
        "status": "pass",
        "reason": "fixture",
        "bug_root": str(tmp_path / "bug"),
        "fix_root": str(tmp_path / "fix"),
        "bug_checkout": {"status": "pass", "ref": "a" * 40},
        "fix_checkout": {"status": "pass", "ref": "b" * 40},
        "test_overlay": {"status": "pass", "files": []},
    }
    (tmp_path / "bug").mkdir()
    (tmp_path / "fix").mkdir()
    calls = 0

    def fake_runner(command, **kwargs):
        nonlocal calls
        del kwargs
        if "-c" in command:
            return subprocess.CompletedProcess(command, 0, stdout="3.11.9\n", stderr="")
        calls += 1
        if calls == 1:
            return subprocess.CompletedProcess(command, 1, stdout="1 failed", stderr="")
        if calls == 2:
            return subprocess.CompletedProcess(command, 0, stdout="1 passed", stderr="")
        return subprocess.CompletedProcess(
            command,
            0,
            stdout="",
            stderr="Ran 0 tests in 0.000s\n\nOK\n",
        )

    result = reproduce_real_bug_case(
        case,
        preparation,
        python_executable=Path(__file__),
        runner=fake_runner,
    )

    assert result["status"] == "fail"
    assert result["acceptance"]["fix_full_regression_passed"] is False


def test_python_runtime_requires_exact_patch_version(tmp_path):
    executable = tmp_path / "python.exe"
    executable.write_text("fixture", encoding="utf-8")

    def fake_runner(command, **kwargs):
        del kwargs
        return subprocess.CompletedProcess(command, 0, stdout="3.11.8\n", stderr="")

    audit = audit_python_runtime(
        executable,
        expected_version="3.11.9",
        runner=fake_runner,
    )

    assert audit["status"] == "fail"
    assert audit["reason"] == "python_version_mismatch"
    assert audit["exact_match"] is False


def _case() -> dict:
    return {
        "case_id": "bugsinpy-demo-1",
        "repository": {"owner_repo": "example/demo"},
        "bug_commit_sha": "a" * 40,
        "fix_commit_sha": "b" * 40,
        "python_version": "3.11.9",
        "test_overlay_paths": ["tests/test_core.py"],
        "targeted_test_commands": [
            ["{python}", "-m", "pytest", "-q", "tests/test_core.py::test_bug"]
        ],
        "regression_command": ["{python}", "-m", "pytest", "-q"],
    }
