from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from code_intelligence_agent.evaluation.release_hygiene_audit import (
    build_release_hygiene_audit,
    render_release_hygiene_audit_markdown,
    write_release_hygiene_audit_artifacts,
)


ROOT = Path(__file__).resolve().parents[1]


def test_release_hygiene_audit_passes_current_git_candidate_set():
    audit = build_release_hygiene_audit(ROOT)

    assert audit["status"] == "pass"
    assert audit["failed_checks"] == []
    assert audit["candidate_file_count"] > 0


def test_release_hygiene_audit_detects_secrets_outputs_and_bad_public_docs(tmp_path):
    (tmp_path / ".gitignore").write_text(
        "outputs/\noutputs_v2/\noutputs_demo/\noutputs_smoke/\noutputs_live/\n"
        "htmlcov/\n.pytest_cache/\n*.docx\n.env\n.env.*\n",
        encoding="utf-8",
    )
    env_name = "CIA_LLM_" + "API_KEY"
    key_prefix = "s" + "k-"
    bad_boundary = "LLM judge " + "可以替代 pytest sandbox"
    (tmp_path / "README.MD").write_text(
        "Generated by ChatGPT\n"
        + bad_boundary
        + "\n"
        + env_name
        + "="
        + key_prefix
        + "12345678901234567890\n",
        encoding="utf-8",
    )
    (tmp_path / "outputs_smoke").mkdir()
    (tmp_path / "outputs_smoke" / "report.json").write_text("{}", encoding="utf-8")
    (tmp_path / "outputs").mkdir()
    (tmp_path / "outputs" / "report.json").write_text("{}", encoding="utf-8")
    (tmp_path / "report.docx").write_text("binary", encoding="utf-8")

    audit = build_release_hygiene_audit(
        tmp_path,
        candidate_paths=[
            "README.MD",
            "outputs/report.json",
            "outputs_smoke/report.json",
            "report.docx",
        ],
    )
    checks = {item["name"]: item for item in audit["checks"]}

    assert audit["status"] == "fail"
    assert checks["no_raw_api_keys"]["passed"] is False
    assert checks["no_tracked_local_outputs_or_binary_docs"]["passed"] is False
    assert checks["public_docs_keep_sandbox_authority_boundary"]["passed"] is False
    assert checks["public_docs_have_no_tool_signature_traces"]["passed"] is False
    assert checks["gitignore_release_outputs_and_secrets"]["passed"] is True


def test_release_hygiene_audit_cli_writes_artifacts(tmp_path):
    output_dir = tmp_path / "audit"
    completed = subprocess.run(
        [
            sys.executable,
            "-m",
            "code_intelligence_agent.evaluation.release_hygiene_audit",
            str(output_dir),
            "--root",
            str(ROOT),
            "--format",
            "json",
            "--require-pass",
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    assert completed.returncode == 0
    payload = json.loads((output_dir / "release_hygiene_audit.json").read_text())
    markdown = (output_dir / "release_hygiene_audit.md").read_text(encoding="utf-8")
    stdout = json.loads(completed.stdout)

    assert payload["status"] == "pass"
    assert stdout["status"] == "pass"
    assert "Release Hygiene Audit" in markdown


def test_release_hygiene_audit_markdown_summarizes_offenders(tmp_path):
    audit = {
        "status": "fail",
        "reason": "release_hygiene_issues_found",
        "candidate_file_count": 1,
        "check_count": 1,
        "passed_check_count": 0,
        "checks": [
            {
                "name": "no_raw_api_keys",
                "passed": False,
                "evidence": "secret found",
                "offenders": ["README.MD"],
            }
        ],
    }

    paths = write_release_hygiene_audit_artifacts(audit, tmp_path)
    markdown = render_release_hygiene_audit_markdown(audit)

    assert Path(paths["release_hygiene_audit_json"]).exists()
    assert Path(paths["release_hygiene_audit_markdown"]).exists()
    assert "README.MD" in markdown
